.TH "musl-ldd" "1" "February 23, 2014" "Linux" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBmusl-ldd\fR
\- print musl shared library depencies
.SH "SYNOPSIS"
.HP 9n
\fBmusl-ldd\fR
\fIFILENAME...\fR
.SH "DESCRIPTION"
\fBmusl-ldd\fR
prints the shared libraries required by the given program or shared library that is dynamicaly linked to the musl libc.
.SH "AUTHORS"
Kevin Bortis <pkgs@bortis.ch>.
.sp
\fBmusl\fR
was written by
.br
Rich Felker <dalias@aerifal.cx>
