.\"
.Dd $Mdocdate: February 23 2014 $
.Dt musl-ldd 1
.Os Linux
.\" SECTION
.Sh NAME
.Nm musl-ldd
.Nd print musl shared library depencies
.\" SECTION
.Sh SYNOPSIS
.Nm musl-ldd
.Ar FILENAME...
.\" SECTION
.Sh DESCRIPTION
.Nm
prints the shared libraries required by the given program or shared library that is dynamicaly linked to the musl libc.
.\" SECTION
.Sh AUTHORS
.An Kevin Bortis Aq pkgs@bortis.ch .

.Nm musl
was written by
.An Rich Felker Aq dalias@aerifal.cx
